version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USER_NAME}/ui:${UI_VER}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${POST_VER}
    networks:
      - back_net 
      - front_net
  comment:
    image: ${USER_NAME}/comment:${COMM_VER}
    networks:
      - back_net 
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
