- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - "vars.yml"
  vars:
      state: present
  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 20
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: "{{ state }}"
     register: disk
   - name: create a network
     gcp_compute_network:
         name: 'default'
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: "{{ state }}"
     register: network
   - name: create a address
     gcp_compute_address:
         name:  "{{ stage_hostname }}-adress"
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: "{{ state }}"
     register: address
   - name: create a instance
     gcp_compute_instance:
         metadata: 
           sshKeys: "{{ deploy_kee }}"
         state: "{{ state }}"
         name: "{{ stage_hostname }}"
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute

     register: instance

   - debug: 
       msg: "{{ instance }}"
   - debug: 
       msg: "{{ instance.networkInterfaces[0] }}"

   - name: del cashe
     command: rm -f /home/gitlab-runner/.ansible/tmp/ansible-gce.cache

   - name: Wait for ssh to come up
     wait_for: host="{{ instance.networkInterfaces[0].accessConfigs[0].natIP }}" port=22 delay=10  timeout=300
     failed_when: false


