version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USER}/ui:1.0
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USER}/post:1.0
    networks:
      - back_net 
      - front_net
  comment:
    build: ./comment
    image: ${USER}/comment:1.0
    networks:
      - back_net 
      - front_net

volumes:
  post_db:

networks:
  reddit:
  back_net:
  front_net:
